In [ ]:
import pandas as pd

a = pd.read_csv("SOCR-HeightWeight.csv")
print("Loaded the dataset Successfully")

Loaded the dataset Successfully

In [ ]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
a.tail()

       Index  Height(Inches)  Weight(Pounds)
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

In [ ]:
a.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [ ]:
a.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [ ]:
from sklearn.model_selection import train_test_split
x=a[['Height(Inches)']]
y=a[['Weight(Pounds)']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(20000, 1)
(5000, 1)
(20000, 1)
(5000, 1)

In [ ]:
x_train

       Height(Inches)
18566        67.95803
17576        66.94689
14197        68.88553
20144        66.87497
9766         72.05521
...               ...
24700        66.91088
1528         67.92717
2734         68.04448
2497         68.12174
24147        67.11686

[20000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_predict=model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_predict)

8.009411363720787

In [ ]:
mean_squared_error(y_test,y_predict)

100.01764503233444

In [ ]:
r2_score(y_test,y_predict)

0.25289871125136365

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"linear.pkl")

['linear.pkl']